insert into store_category (category_id, "name", parent_id) values (1, 'Synchronised object-oriented solution', null);
insert into store_category (category_id, "name", parent_id) values (2, 'Right-sized human-resource leverage', 1);
insert into store_category (category_id, "name", parent_id) values (3, 'Public-key eco-centric archive', 1);
insert into store_category (category_id, "name", parent_id) values (4, 'Mandatory stable standardization', null);
insert into store_category (category_id, "name", parent_id) values (5, 'Customer-focused national contingency', null);
insert into store_category (category_id, "name", parent_id) values (6, 'Realigned systemic attitude', null);
insert into store_category (category_id, "name", parent_id) values (7, 'Balanced demand-driven synergy', null);
insert into store_category (category_id, "name", parent_id) values (8, 'Programmable responsive throughput', 7);
insert into store_category (category_id, "name", parent_id) values (9, 'Centralized fault-tolerant array', 8);
insert into store_category (category_id, "name", parent_id) values (10, 'Cross-group client-server local area network', 8);
insert into store_category (category_id, "name", parent_id) values (11, 'Digitized modular architecture', 10);
insert into store_category (category_id, "name", parent_id) values (12, 'De-engineered optimal capacity', 10);
insert into store_category (category_id, "name", parent_id) values (13, 'Customer-focused stable firmware', 7);
insert into store_category (category_id, "name", parent_id) values (14, 'Ergonomic empowering database', null);
insert into store_category (category_id, "name", parent_id) values (15, 'Implemented dynamic artificial intelligence', 14);
insert into store_category (category_id, "name", parent_id) values (16, 'Realigned bandwidth-monitored complexity', 15);
insert into store_category (category_id, "name", parent_id) values (17, 'Function-based bandwidth-monitored utilisation', 15);
insert into store_category (category_id, "name", parent_id) values (18, 'Programmable motivating budgetary management', 14);
insert into store_category (category_id, "name", parent_id) values (19, 'User-centric full-range application', 18);
insert into store_category (category_id, "name", parent_id) values (20, 'Synergistic regional matrices', 19);
insert into store_category (category_id, "name", parent_id) values (21, 'Adaptive eco-centric success', 19);
insert into store_category (category_id, "name", parent_id) values (22, 'Mandatory bottom-line application', 18);
insert into store_category (category_id, "name", parent_id) values (23, 'Persistent maximized database', null);
insert into store_category (category_id, "name", parent_id) values (24, 'Centralized composite Graphical User Interface', null);
insert into store_category (category_id, "name", parent_id) values (25, 'Cross-platform maximized success', null);
insert into store_category (category_id, "name", parent_id) values (26, 'Face to face transitional array', 25);
insert into store_category (category_id, "name", parent_id) values (27, 'Future-proofed didactic system engine', 26);
insert into store_category (category_id, "name", parent_id) values (28, 'Universal discrete interface', 26);
insert into store_category (category_id, "name", parent_id) values (29, 'Profound needs-based interface', 28);
insert into store_category (category_id, "name", parent_id) values (30, 'Configurable bifurcated concept', 28);
insert into store_category (category_id, "name", parent_id) values (31, 'Open-architected bottom-line frame', 25);
insert into store_category (category_id, "name", parent_id) values (32, 'Versatile analyzing synergy', 31);
insert into store_category (category_id, "name", parent_id) values (33, 'Grass-roots actuating solution', 32);
insert into store_category (category_id, "name", parent_id) values (34, 'Intuitive human-resource matrices', 32);
insert into store_category (category_id, "name", parent_id) values (35, 'Organized asynchronous emulation', 31);
insert into store_category (category_id, "name", parent_id) values (36, 'Diverse composite success', 35);
insert into store_category (category_id, "name", parent_id) values (37, 'Innovative holistic moratorium', 35);
insert into store_category (category_id, "name", parent_id) values (38, 'Robust eco-centric focus group', null);
insert into store_category (category_id, "name", parent_id) values (39, 'Optional coherent approach', null);
insert into store_category (category_id, "name", parent_id) values (40, 'Managed well-modulated implementation', null);
insert into store_category (category_id, "name", parent_id) values (41, 'Configurable grid-enabled data-warehouse', 40);
insert into store_category (category_id, "name", parent_id) values (42, 'Balanced grid-enabled moderator', 41);
insert into store_category (category_id, "name", parent_id) values (43, 'Enhanced global strategy', 42);
insert into store_category (category_id, "name", parent_id) values (44, 'Organized contextually-based flexibility', 42);
insert into store_category (category_id, "name", parent_id) values (45, 'Re-engineered secondary paradigm', 41);
insert into store_category (category_id, "name", parent_id) values (46, 'Object-based 3rd generation model', 45);
insert into store_category (category_id, "name", parent_id) values (47, 'Object-based content-based orchestration', 45);
insert into store_category (category_id, "name", parent_id) values (48, 'Team-oriented static approach', 40);
insert into store_category (category_id, "name", parent_id) values (49, 'Operative incremental service-desk', 48);
insert into store_category (category_id, "name", parent_id) values (50, 'Face to face contextually-based collaboration', 49);
insert into store_category (category_id, "name", parent_id) values (51, 'Streamlined next generation database', 49);
insert into store_category (category_id, "name", parent_id) values (52, 'Balanced systemic Graphic Interface', 48);
insert into store_category (category_id, "name", parent_id) values (53, 'Optimized 6th generation toolset', 52);
insert into store_category (category_id, "name", parent_id) values (54, 'Multi-tiered value-added artificial intelligence', 52);
insert into store_category (category_id, "name", parent_id) values (55, 'Vision-oriented user-facing encryption', null);
insert into store_category (category_id, "name", parent_id) values (56, 'Synergistic composite strategy', 55);
insert into store_category (category_id, "name", parent_id) values (57, 'Assimilated global interface', 55);
insert into store_category (category_id, "name", parent_id) values (58, 'Virtual tertiary extranet', 57);
insert into store_category (category_id, "name", parent_id) values (59, 'Robust incremental implementation', 57);
insert into store_category (category_id, "name", parent_id) values (60, 'Enhanced demand-driven structure', 59);
insert into store_category (category_id, "name", parent_id) values (61, 'Synergistic explicit structure', 59);
insert into store_category (category_id, "name", parent_id) values (62, 'Cloned fresh-thinking archive', null);
insert into store_category (category_id, "name", parent_id) values (63, 'Intuitive encompassing toolset', 62);
insert into store_category (category_id, "name", parent_id) values (64, 'Visionary interactive structure', 62);
insert into store_category (category_id, "name", parent_id) values (65, 'Polarised 5th generation alliance', 64);
insert into store_category (category_id, "name", parent_id) values (66, 'Business-focused maximized approach', 64);
insert into store_category (category_id, "name", parent_id) values (67, 'Exclusive responsive system engine', 66);
insert into store_category (category_id, "name", parent_id) values (68, 'Distributed encompassing info-mediaries', 66);
insert into store_category (category_id, "name", parent_id) values (69, 'Grass-roots real-time portal', null);
insert into store_category (category_id, "name", parent_id) values (70, 'Centralized intermediate groupware', null);
insert into store_category (category_id, "name", parent_id) values (71, 'Reduced hybrid hub', null);
insert into store_category (category_id, "name", parent_id) values (72, 'Advanced solution-oriented projection', null);
insert into store_category (category_id, "name", parent_id) values (73, 'Customizable directional collaboration', 72);
insert into store_category (category_id, "name", parent_id) values (74, 'Extended non-volatile paradigm', 72);
insert into store_category (category_id, "name", parent_id) values (75, 'Optional client-server customer loyalty', 74);
insert into store_category (category_id, "name", parent_id) values (76, 'Assimilated solution-oriented workforce', 74);
insert into store_category (category_id, "name", parent_id) values (77, 'Right-sized 24 hour projection', 76);
insert into store_category (category_id, "name", parent_id) values (78, 'Exclusive intermediate superstructure', 76);
insert into store_category (category_id, "name", parent_id) values (79, 'Customizable leading edge time-frame', null);
insert into store_category (category_id, "name", parent_id) values (80, 'Customer-focused secondary open architecture', null);
insert into store_category (category_id, "name", parent_id) values (81, 'Exclusive regional task-force', null);
insert into store_category (category_id, "name", parent_id) values (82, 'Multi-layered bifurcated software', null);
insert into store_category (category_id, "name", parent_id) values (83, 'Reverse-engineered asynchronous website', 82);
insert into store_category (category_id, "name", parent_id) values (84, 'Public-key multimedia archive', 82);
insert into store_category (category_id, "name", parent_id) values (85, 'Synergistic background success', null);
insert into store_category (category_id, "name", parent_id) values (86, 'Managed next generation framework', null);
insert into store_category (category_id, "name", parent_id) values (87, 'Multi-lateral analyzing Graphical User Interface', null);
insert into store_category (category_id, "name", parent_id) values (88, 'Extended responsive groupware', 87);
insert into store_category (category_id, "name", parent_id) values (89, 'Ergonomic intangible system engine', 88);
insert into store_category (category_id, "name", parent_id) values (90, 'Sharable motivating firmware', 88);
insert into store_category (category_id, "name", parent_id) values (91, 'Integrated mission-critical concept', 90);
insert into store_category (category_id, "name", parent_id) values (92, 'Optional intangible benchmark', 90);
insert into store_category (category_id, "name", parent_id) values (93, 'Persevering incremental toolset', 87);
insert into store_category (category_id, "name", parent_id) values (94, 'Enhanced intangible middleware', 93);
insert into store_category (category_id, "name", parent_id) values (95, 'Open-source reciprocal support', 94);
insert into store_category (category_id, "name", parent_id) values (96, 'Reduced uniform data-warehouse', 94);
insert into store_category (category_id, "name", parent_id) values (97, 'Total client-driven collaboration', 93);
insert into store_category (category_id, "name", parent_id) values (98, 'De-engineered empowering support', null);
insert into store_category (category_id, "name", parent_id) values (99, 'Robust high-level internet solution', 98);
insert into store_category (category_id, "name", parent_id) values (100, 'Synchronised mobile framework', 99);
insert into store_category (category_id, "name", parent_id) values (101, 'Distributed encompassing orchestration', 99);
insert into store_category (category_id, "name", parent_id) values (102, 'Digitized analyzing methodology', 101);
insert into store_category (category_id, "name", parent_id) values (103, 'Devolved non-volatile monitoring', 101);
insert into store_category (category_id, "name", parent_id) values (104, 'Sharable mission-critical synergy', 98);
insert into store_category (category_id, "name", parent_id) values (105, 'Visionary incremental interface', null);
insert into store_category (category_id, "name", parent_id) values (106, 'Innovative tertiary task-force', 105);
insert into store_category (category_id, "name", parent_id) values (107, 'User-centric asymmetric synergy', 106);
insert into store_category (category_id, "name", parent_id) values (108, 'Quality-focused coherent policy', 107);
insert into store_category (category_id, "name", parent_id) values (109, 'Synchronised intangible architecture', 107);
insert into store_category (category_id, "name", parent_id) values (110, 'Reverse-engineered empowering collaboration', 106);
insert into store_category (category_id, "name", parent_id) values (111, 'Versatile dedicated superstructure', 105);
insert into store_category (category_id, "name", parent_id) values (112, 'Customer-focused tertiary help-desk', null);
insert into store_category (category_id, "name", parent_id) values (113, 'Object-based 4th generation knowledge base', 112);
insert into store_category (category_id, "name", parent_id) values (114, 'Networked systemic archive', 113);
insert into store_category (category_id, "name", parent_id) values (115, 'Up-sized executive data-warehouse', 113);
insert into store_category (category_id, "name", parent_id) values (116, 'Diverse modular definition', 112);
insert into store_category (category_id, "name", parent_id) values (117, 'Multi-layered discrete encoding', null);
insert into store_category (category_id, "name", parent_id) values (118, 'Integrated incremental emulation', 117);
insert into store_category (category_id, "name", parent_id) values (119, 'Enhanced systemic alliance', 117);
insert into store_category (category_id, "name", parent_id) values (120, 'Horizontal asynchronous extranet', 119);
insert into store_category (category_id, "name", parent_id) values (121, 'Phased systematic toolset', 120);
insert into store_category (category_id, "name", parent_id) values (122, 'Compatible static challenge', 120);
insert into store_category (category_id, "name", parent_id) values (123, 'Organized needs-based parallelism', 119);
insert into store_category (category_id, "name", parent_id) values (124, 'Diverse hybrid forecast', 123);
insert into store_category (category_id, "name", parent_id) values (125, 'Adaptive zero tolerance algorithm', 123);
insert into store_category (category_id, "name", parent_id) values (126, 'Vision-oriented multimedia core', null);
insert into store_category (category_id, "name", parent_id) values (127, 'Public-key clear-thinking pricing structure', null);
insert into store_category (category_id, "name", parent_id) values (128, 'Focused disintermediate process improvement', null);
insert into store_category (category_id, "name", parent_id) values (129, 'Synergized transitional matrix', 128);
insert into store_category (category_id, "name", parent_id) values (130, 'Multi-layered stable framework', 128);
insert into store_category (category_id, "name", parent_id) values (131, 'Secured cohesive Graphical User Interface', 130);
insert into store_category (category_id, "name", parent_id) values (132, 'Cross-group real-time array', 131);
insert into store_category (category_id, "name", parent_id) values (133, 'Multi-layered mission-critical neural-net', 131);
insert into store_category (category_id, "name", parent_id) values (134, 'Persevering optimal intranet', 130);
insert into store_category (category_id, "name", parent_id) values (135, 'De-engineered 5th generation productivity', null);
insert into store_category (category_id, "name", parent_id) values (136, 'Advanced scalable middleware', null);
insert into store_category (category_id, "name", parent_id) values (137, 'Adaptive zero defect pricing structure', 136);
insert into store_category (category_id, "name", parent_id) values (138, 'Grass-roots real-time support', 137);
insert into store_category (category_id, "name", parent_id) values (139, 'Focused bifurcated Graphical User Interface', 137);
insert into store_category (category_id, "name", parent_id) values (140, 'Self-enabling actuating leverage', 139);
insert into store_category (category_id, "name", parent_id) values (141, 'Polarised 24 hour matrix', 139);
insert into store_category (category_id, "name", parent_id) values (142, 'Stand-alone 3rd generation local area network', 136);
insert into store_category (category_id, "name", parent_id) values (143, 'Realigned bottom-line complexity', 142);
insert into store_category (category_id, "name", parent_id) values (144, 'Public-key systematic parallelism', 143);
insert into store_category (category_id, "name", parent_id) values (145, 'Progressive neutral capability', 143);
insert into store_category (category_id, "name", parent_id) values (146, 'Optional client-server throughput', 142);
insert into store_category (category_id, "name", parent_id) values (147, 'Streamlined asynchronous benchmark', null);
insert into store_category (category_id, "name", parent_id) values (148, 'Secured executive initiative', 147);
insert into store_category (category_id, "name", parent_id) values (149, 'Open-architected directional infrastructure', 147);
insert into store_category (category_id, "name", parent_id) values (150, 'Balanced transitional matrix', 149);
